schema_version = "1.0.0"
version = "1.0.0"
id = "lrexporter"
name = "LR Exporter"
tagline = "Aims to simplify object importing and exporting from Blender."
maintainer = "Lukas Reznicek <lukasreznicek@gmail.com>"
type = "add-on"
tags = ["object"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
#website = ""
copyright = ["2024 Lukas Reznicek"]
